#!/bin/bash

# for this assignment curl tools will be used to transfer data from or to github server
# cURL is a tool that provides a library and command-line tool for transferring data using various protocols

# to make a basic get request to my public info on github
curl https://api.github.com/users/olawalequest

# to include HTTP header information in my public info output on github
curl --include https://api.github.com/users/olawalequest

# Pass user credential to basic auth to access protected resources associated with user github profile
# the below line will request for the user password on the command line
curl --user "olawalequest" https://api.github.com/users/caspyin
